spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  sleuth:
    sampler:
      percentage: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  profiles:
    active: native
  rabbitmq:
    host: ${RABBIT_HOST:192.168.2.139}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}

server:
  port: 1002

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://192.168.2.139:1001/eureka}

management:
  security:
    enabled: false
