info:
  profile: default
myconfig:
  tangly: demo2-config-deault-zipkin
# 通过消息中间件获取trace
spring:
  rabbitmq:
    host: ${RABBIT_HOST:192.168.2.139}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_USERNAME:guest}
