spring:
  application:
    name: hystrix-dashboard
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka
server:
  port: 1000

turbine:
  aggregator:
    cluster-config: default     #需要监控的服务集群名
  app-config: biz-demo,biz-demo-2    #需要监控的服务名
  cluster-name-expression: new String("default")