server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  hystrix:
    enabled: true