spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
    bus:
      trace:
        enabled: true
  profiles:
    active: native
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 1002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'
