spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
    active: native

server:
  port: 1002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka
